PORTNAME=	ssh-audit
DISTVERSIONPREFIX=	v
DISTVERSION=	2.4.0
CATEGORIES=	security
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	pkubaj@FreeBSD.org
COMMENT=	SSH server auditing

LICENSE=	MIT

USES=		python
USE_GITHUB=	yes
GH_ACCOUNT=	jtesta
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
