PORTNAME=	FreeBSD-ports
PORTVERSION=	0.0.9
CATEGORIES=	ports-mgmt python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Parse FreeBSD Ports INDEX, provide search API

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
