PORTNAME=	phybs
PORTVERSION=	20140717
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	LOCAL/des

MAINTAINER=	des@FreeBSD.org
COMMENT=	Disk benchmarking utility

LICENSE=	BSD2CLAUSE

PLIST_FILES=	bin/phybs share/man/man1/phybs.1.gz

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
