# Created by: Ryan Steinmetz <zi@FreeBSD.org>

PORTNAME=	climate_control
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Modify your ENV

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
