# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>

PORTNAME=	jsonrpclib-pelix
PORTVERSION=	0.4.2
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	JSON-RPC over HTTP that mirrors xmlrpclib syntax

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	distutils autoplist

NO_ARCH=	yes

.include <bsd.port.mk>
