PORTNAME=	fcgi
PORTVERSION=	0.9.2.1
CATEGORIES=	www ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	FastCGI library for Ruby

LICENSE=	MIT

LIB_DEPENDS=	libfcgi.so:www/fcgi

USES=		gem

.include <bsd.port.mk>
