PORTNAME=	mkrf
PORTVERSION=	0.2.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Replacement to mkmf generates Rakefiles to build C Extensions

LICENSE=	MIT

USES=		gem python

.include <bsd.port.mk>
