# Created by: Wen Heping <wenheping@gmail.com>

PORTNAME=	prawn-core
PORTVERSION=	0.8.4
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Core of Rubygem-prawn

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
