PORTNAME=	showfont
PORTVERSION=	1.0.5
PORTREVISION=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Font dumper for the X font server
WWW=		https://www.x.org/

USES=		xorg xorg-cat:app
USE_XORG=	libfs xorgproto


PLIST_FILES=	bin/showfont share/man/man1/showfont.1.gz

.include <bsd.port.mk>
