# Created by: renchap@cocoa-x.com

PORTNAME=	moneta
PORTVERSION=	1.4.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Unified interface to key/value stores

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem shebangfix

NO_ARCH=	yes

SHEBANG_FILES=	script/start-couchdb \
		script/start-services

.include <bsd.port.mk>
