# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>

PORTNAME=	uritools
PORTVERSION=	3.0.2
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	RFC 3986 compliant, Unicode-aware, scheme-agnostic replacement for urlparse

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
