# Created by: Ryan Steinmetz <zi@FreeBSD.org>

PORTNAME=	mysql
PORTVERSION=	2.9.1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL API module for Ruby

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

USES=		gem mysql

.include <bsd.port.mk>
