# Created by: Steve Wills <swills@FreeBSD.org>

PORTNAME=	kgio
PORTVERSION=	2.11.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides non-blocking I/O methods

LICENSE=	LGPL21+

USES=		gem

.include <bsd.port.mk>
