PORTNAME=	ddmetrics
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Non-timeseries measurements for Ruby programs

LICENSE=	MIT

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
